[package]
name = "t4_rsa_cipher"
version = "0.1.0"
edition = "2021"

[dependencies]
bigint = { path = "../bigint" }
num-bigint = { version = "0.4.6", features = ["rand"] }
num-traits = "0.2.19"
rand = "0.8.5"
